### ISSUE TITLE
Doesn't work in my case

### ISSUE THREAD

**Issue by wesleymacente** [nordhagen/jquery-zload#1]
I tried implement this plugin in livlight.com.br but the background doesn't appear. I don't know if zload works with horizontal scrolling.. 

Something like this:

section id="emcasa" class="section" data-original="http://livlight.com.br/storage/casa/1/emcasa.jpg"

$('#emcasa').zload();

It's correct?

Thanks!

**Comment by nordhagen** [comment]
Your implementation is correct. But as noted in the readme, zload is only designed for vertical scrolling. However it should be trivial to add horizontal scrolling capability. You are welcome to submit a pull request for such a feature!

**Comment by wesleymacente** [comment]
Okey!

I'll try to implement this on a horizontal scroll. If I make it work I'll post here.

Thanks so much!
